spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: mxzzcloud-config-client
eureka:
  client: 
    service-url:
      defaultZone: http://hlxd:82777999@eureka-dev.com:7001/eureka
---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: mxzzcloud-config-client
eureka:
  client: 
    service-url:
      defaultZone: http://hlxd:82777999@eureka-beta.com:7001/eureka